apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: dns-relay
  name: dns-relay-release
spec:
  failedBuildsHistoryLimit: 1
  output:
    pushSecret:
      name: openpaas.eu-central-1.aws.artifactory
    to:
      kind: DockerImage
      # put some semantic version here
      name: ats-openpaas-cc-private-repo-docker.docker.artifactory.pink.eu-central-1.aws.openpaas.axa-cloud.com/openpaas/dns-relay:v1.2.3
  postCommit: {}
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/MichaelVoegele/dns-relay.git
    type: Git
  strategy:
    dockerStrategy:
      buildArgs:
        - name: HTTP_PROXY
          value: http://egress-http-proxy:8080
        - name: HTTPS_PROXY
          value: http://egress-http-proxy:8080
      from:
        kind: ImageStreamTag
        name: ubi8:latest
    type: Docker
  successfulBuildsHistoryLimit: 1
